[package]
name = "fastlanez-sys"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
paste = "1.0.14"
seq-macro = "0.3.5"

[build-dependencies]
bindgen = "0.69.1"
walkdir = "2.4.0"