[package]
name = "fastlanez-sys"
version = "0.1.0"
edition = "2021"
links = "fastlanez"

[lints]
workspace = true

[dependencies]
arrayref = "0.3.7"
paste = "1.0.14"
seq-macro = "0.3.5"
uninit = "0.6.2"

[build-dependencies]
bindgen = "0.69.1"
walkdir = "2.4.0"