[workspace]
members = [
    "pyenc",
    "pyspiral",
    "rust/codecz",
    "rust/codecz-sys",
    "rust/enc",
    "rust/enc-alp",
    "rust/enc-bench",
    "rust/enc-dict",
    "rust/enc-ffor",
    "rust/enc-patched",
    "rust/enc-ree",
    "rust/enc-roaring",
    "rust/enc-zigzag",
    "rust/spiral-alloc",
]
resolver = "2"

[workspace.lints.clippy]
all = "deny"

[profile.dev]
# Need this for linkme crate to work. See https://github.com/dtolnay/linkme/issues/61
codegen-units = 1
