[workspace]
members = [
    "bench-vortex",
    "build-vortex",
    "fastlanez",
    "fastlanez-sys",
    "pyvortex",
    "vortex-alp",
    "vortex-array",
    "vortex-datetime-parts",
    "vortex-dict",
    "vortex-error",
    "vortex-fastlanes",
    "vortex-flatbuffers",
    "vortex-ipc",
    "vortex-ree",
    "vortex-roaring",
    "vortex-dtype",
    "vortex-zigzag",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
homepage = "https://github.com/fulcrum-so/vortex"
repository = "https://github.com/fulcrum-so/vortex"
authors = ["Robert Kruszewski <robert@fulcrum.so>, Nicholas Gates <nick@fulcrum.so>, Will Manning <will@fulcrum.so>"]
license = "Apache-2.0"
keywords = ["vortex"]
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2021"
rust-version = "1.76"

[workspace.dependencies]
ahash = "0.8.11"
allocator-api2 = "0.2.16"
arrayref = "0.3.7"
arrow = { version = "51.0.0", features = ["pyarrow"] }
arrow-array = "51.0.0"
arrow-buffer = "51.0.0"
arrow-csv = "51.0.0"
arrow-data = "51.0.0"
arrow-ipc = "51.0.0"
arrow-schema = "51.0.0"
arrow-select = "51.0.0"
bindgen = "0.69.4"
bzip2 = "0.4.4"
criterion = { version = "0.5.1", features = ["html_reports"] }
croaring = "1.0.1"
csv = "1.3.0"
divan = "0.1.14"
duckdb = { version = "0.10.1", features = ["bundled"] }
enum-iterator = "2.0.0"
enum_dispatch = "0.3.13"
fallible-iterator = "0.3.0"
flatbuffers = "23.5.26"
flatc = "0.2.2"
flexbuffers = "2.0.0"
fs_extra = "1.3.0"
getrandom = "0.2.14"
half = { version = "^2", features = ["std", "num-traits"] }
hashbrown = "0.14.3"
humansize = "2.1.3"
itertools = "0.12.1"
lazy_static = "1.4.0"
leb128 = "0.2.5"
log = "0.4.21"
num-traits = "0.2.18"
num_enum = "0.7.2"
parquet = "51.0.0"
paste = "1.0.14"
pyo3 = { version = "0.20.2", features = ["extension-module", "abi3-py311"] }
pyo3-log = "0.9.0"
rand = "0.8.5"
reqwest = { version = "0.12.0", features = ["blocking"] }
seq-macro = "0.3.5"
serde = "1.0.197"
simplelog = { version = "0.12.2", features = ["paris"] }
thiserror = "1.0.58"
tokio = "1.37.0"
uninit = "0.6.2"
uuid = "1.8.0"
walkdir = "2.5.0"
zigzag = "0.1.0"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
