[workspace]
members = [
    "pyenc",
    "codecz",
    "codecz-sys",
    "enc",
    "enc-alp",
    "enc-bench",
    "enc-dict",
    "enc-ffor",
    "enc-ree",
    "enc-roaring",
    "enc-zigzag",
    "spiral-alloc",
]
resolver = "2"

[workspace.lints.clippy]
all = "deny"

[profile.dev]
# Need this for linkme crate to work. See https://github.com/dtolnay/linkme/issues/61
codegen-units = 1
