[workspace]
members = [
    "bench-vortex",
    "fastlanez",
    "fastlanez-sys",
    "pyvortex",
    "vortex-alloc",
    #"vortex-alp",
    "vortex-array",
    #"vortex-datetime",
    "vortex-dict",
    "vortex-error",
    "vortex-fastlanes",
    "vortex-flatbuffers",
    "vortex-ipc",
    "vortex-ree",
    #"vortex-roaring",
    "vortex-schema",
    #"vortex-zigzag",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
homepage = "https://github.com/fulcrum-so/vortex"
repository = "https://github.com/fulcrum-so/vortex"
authors = ["Robert Kruszewski <robert@fulcrum.so>, Nicholas Gates <nick@fulcrum.so>, Will Manning <will@fulcrum.so>"]
license = "Apache-2.0"
keywords = ["vortex"]
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2021"
rust-version = "1.76"

[workspace.dependencies]
ahash = "0.8.11"
allocator-api2 = "0.2.16"
arrayref = "0.3.7"
arrow = { version = "51.0.0", features = ["pyarrow"] }
arrow-array = "51.0.0"
arrow-buffer = "51.0.0"
arrow-select = "51.0.0"
arrow-schema = "51.0.0"
bindgen = "0.69.4"
criterion = { version = "0.5.1", features = ["html_reports"] }
croaring = "1.0.1"
divan = "0.1.14"
enum_dispatch = "0.3.13"
enum-iterator = "2.0.0"
flatbuffers = "23.5.26"
flexbuffers = "2.0.0"
flatc = "0.2.2"
fs_extra = "1.3.0"
half = { version = "^2", features = ["std", "num-traits"] }
hashbrown = "0.14.3"
humansize = "2.1.3"
itertools = "0.12.1"
leb128 = "0.2.5"
linkme = "0.3.25"
log = "0.4.21"
num-traits = "0.2.18"
num_enum = "0.7.2"
parquet = "51.0.0"
paste = "1.0.14"
pyo3 = { version = "0.20.2", features = ["extension-module", "abi3-py311"] }
pyo3-log = "0.9.0"
rand = "0.8.5"
reqwest = { version = "0.12.0", features = ["blocking"] }
seq-macro = "0.3.5"
serde = "1.0.197"
simplelog = { version = "0.12.2", features = ["paris"] }
thiserror = "1.0.58"
uninit = "0.6.2"
walkdir = "2.5.0"
zigzag = "0.1.0"
bzip2 = "0.4.4"
csv = "1.3.0"
arrow-csv = "51.0.0"
lazy_static = "1.4.0"
uuid = "1.8.0"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"

[profile.dev]
# Need this for linkme crate to work. See https://github.com/dtolnay/linkme/issues/61
codegen-units = 1
