[workspace]
members = [
    "bench-vortex",
    "codecz",
    "codecz-sys",
    "fastlanez-sys",
    "pyvortex",
    "vortex",
    "vortex-alloc",
    "vortex-alp",
    "vortex-dict",
    "vortex-ffor",
    "vortex-ree",
    "vortex-roaring",
    "vortex-zigzag",
]
resolver = "2"

[workspace.lints.clippy]
all = "deny"

[profile.dev]
# Need this for linkme crate to work. See https://github.com/dtolnay/linkme/issues/61
codegen-units = 1
