[workspace]
members = [
    "bench-vortex",
    "fastlanez-sys",
    "pyvortex",
    "vortex-alloc",
    "vortex-alp",
    "vortex-array",
    "vortex-datetime",
    "vortex-dict",
    "vortex-fastlanes",
    "vortex-ree",
    "vortex-roaring",
    "vortex-schema",
    "vortex-zigzag",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
homepage = "https://github.com/fulcrum-so/vortex"
repository = "https://github.com/fulcrum-so/vortex"
authors = ["Robert Kruszewski <robert@fulcrum.so>, Nicholas Gates <nick@fulcrum.so>, Will Manning <will@fulcrum.so>"]
license = "Apache-2.0"
keywords = ["vortex"]
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Carsgo.toml",
]
edition = "2021"
rust-version = "1.76"

[workspace.dependencies]
allocator-api2 = "0.2.16"
arrow = { version = "51.0.0", features = ["pyarrow"] }
arrow-array = "51.0.0"
arrow-buffer = "51.0.0"
arrow-schema = "51.0.0"
half = { version = "2.4.0", features = ["std", "num-traits"] }
humansize = "2.1.3"
itertools = "0.12.1"
leb128 = "0.2.5"
linkme = "0.3.25"
log = "0.4.21"
num-traits = "0.2.18"
num_enum = "0.7.2"
parquet = "51.0.0"
paste = "1.0.14"
rand = "0.8.5"
thiserror = "1.0.58"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"

[profile.dev]
# Need this for linkme crate to work. See https://github.com/dtolnay/linkme/issues/61
codegen-units = 1
