[workspace]
members = [
    "bench-vortex",
    "codecz",
    "codecz-sys",
    "fastlanez-sys",
    "pyvortex",
    "vortex",
    "vortex-alloc",
    "vortex-alp",
    "vortex-dict",
    "vortex-fastlanes",
    "vortex-ffor",
    "vortex-ree",
    "vortex-roaring",
    "vortex-zigzag",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
homepage = "https://github.com/apache/arrow-rs"
repository = "https://github.com/apache/arrow-rs"
authors = ["Apache Arrow <dev@arrow.apache.org>"]
license = "Apache-2.0"
keywords = ["arrow"]
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2021"
rust-version = "1.62"


[workspace.lints.clippy]
all = "deny"

[profile.dev]
# Need this for linkme crate to work. See https://github.com/dtolnay/linkme/issues/61
codegen-units = 1
