[package]
name = "codecz-sys"
version = "0.1.0"
edition = "2021"
links = "codecz"

[lints]
workspace = true

[dependencies]
safe-transmute = "0.11.2"
spiral-alloc = { version = "0.1.0", path = "../spiral-alloc" }

[build-dependencies]
bindgen = "0.69.1"
walkdir = "2.4.0"
