[package]
name = "vortex-datetime-parts"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
vortex-array = { "path" = "../vortex-array" }
vortex-error = { path = "../vortex-error" }
vortex-schema = { "path" = "../vortex-schema" }
linkme = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
