[package]
name = "vortex-bench"
version = { workspace = true }
description = "End to end vortex benchmarks"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
arrow-array = "50.0.0"
vortex-array = { path = "../vortex-array" }
vortex-alp = { path = "../vortex-alp" }
vortex-dict = { path = "../vortex-dict" }
vortex-fastlanes = { path = "../vortex-fastlanes" }
vortex-ree = { path = "../vortex-ree" }
vortex-roaring = { path = "../vortex-roaring" }
vortex-zigzag = { path = "../vortex-zigzag" }
itertools = "0.12.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
log = "0.4.20"
parquet = "50.0.0"
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["blocking"] }
simplelog = { version = "0.12.1", features = ["paris"] }

[[bench]]
name = "compress_benchmark"
harness = false