[package]
name = "bench-vortex"
version = { workspace = true }
description = "End to end vortex benchmarks"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
#vortex-alp = { path = "../vortex-alp" }
vortex-roaring = { path = "../vortex-roaring" }
#vortex-zigzag = { path = "../vortex-zigzag" }
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-csv = { workspace = true }
arrow-data = { workspace = true }
arrow-select = { workspace = true }
bzip2 = { workspace = true }
csv = { workspace = true }
enum-iterator = { workspace = true }
fs_extra = { workspace = true }
humansize = { workspace = true }
itertools = { workspace = true }
lance = { version = "0.10.5", features = [] }
lance-arrow-array = { package = "arrow-array", version = "50.0" }
lance-parquet = { package = "parquet", version = "50.0", features = [] }
lazy_static = { workspace = true }
log = { workspace = true }
parquet = { workspace = true, features = [] }
reqwest = { workspace = true }
simplelog = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
vortex-alp = { path = "../vortex-alp" }
vortex-array = { path = "../vortex-array" }
vortex-datetime-parts = { path = "../vortex-datetime-parts" }
vortex-dict = { path = "../vortex-dict" }
vortex-error = { path = "../vortex-error", features = ["parquet"] }
vortex-fastlanes = { path = "../vortex-fastlanes" }
vortex-ipc = { path = "../vortex-ipc" }
vortex-ree = { path = "../vortex-ree" }
vortex-schema = { path = "../vortex-schema" }

[dev-dependencies]
criterion = { workspace = true }


[[bench]]
name = "compress_benchmark"
harness = false

[[bench]]
name = "random_access"
harness = false
