[package]
name = "bench-vortex"
version = { workspace = true }
description = "End to end vortex benchmarks"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
arrow-array = { workspace = true }
vortex-array = { path = "../vortex-array" }
vortex-datetime = { path = "../vortex-datetime" }
vortex-alp = { path = "../vortex-alp" }
vortex-dict = { path = "../vortex-dict" }
vortex-fastlanes = { path = "../vortex-fastlanes" }
vortex-ree = { path = "../vortex-ree" }
vortex-roaring = { path = "../vortex-roaring" }
vortex-schema = { path = "../vortex-schema" }
vortex-zigzag = { path = "../vortex-zigzag" }
itertools = { workspace = true }
reqwest = { workspace = true }
parquet = { workspace = true }
log = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
simplelog = { workspace = true }

[[bench]]
name = "compress_benchmark"
harness = false