[package]
name = "vortex"
version = "0.1.0"
edition = "2021"

[lib]
name = "vortex"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
allocator-api2 = "0.2.16"
arrow = { version = "50.0.0", features = ["pyarrow"] }
dyn-clone = "1.0.16"
half = "2.3.1"
humansize = "2.1.3"
itertools = "0.12.1"
leb128 = "0.2.5"
linkme = "0.3.23"
log = "0.4.20"
num-traits = "0.2.18"
num_enum = "0.7.2"
once_cell = "1.19.0"
polars-arrow = { version = "0.37.0", features = ["arrow_rs"] }
polars-core = "0.37.0"
polars-ops = { version = "0.37.0", features = ["search_sorted"] }
rand = { version = "0.8.5", features = [] }
rayon = "1.8.1"
roaring = "0.10.3"
vortex-alloc = { version = "0.1.0", path = "../vortex-alloc" }
thiserror = "1.0.57"
