[package]
name = "vortex-zigzag"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
vortex = { "path" = "../vortex" }
linkme = "0.3.22"
vortex-alloc = { version = "0.1.0", path = "../vortex-alloc" }
zigzag = "0.1.0"
