[package]
name = "enc-zigzag"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
enc = { "path" = "../enc" }
linkme = "0.3.22"
spiral-alloc = { version = "0.1.0", path = "../spiral-alloc" }
zigzag = "0.1.0"
