[package]
name = "enc-ree"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "50.0.0" }
codecz = { path = "../codecz" }
enc = { path = "../enc" }
linkme = "0.3.22"
half = "2.3.1"
num-traits = "0.2.17"
itertools = "0.10.5"
