name: 'Setup Zig'
description: 'Toolchain setup and Initial compilation'
runs:
  using: "composite"
  steps:
    - name: Zig Version
      id: zig-version
      shell: bash
      run: echo "version=$(cat .zig-version | tr -d '\n ')" >> $GITHUB_OUTPUT

    - name: Zig Setup
      uses: engineerd/configurator@v0.0.9
      with:
        name: zig
        url: "https://ziglang.org/builds/zig-linux-x86_64-${{ steps.zig-version.outputs.version }}.tar.xz"
        pathInArchive: zig
