name: 'Setup Zig'
description: 'Toolchain setup and Initial compilation'
runs:
  using: "composite"
  steps:
    - name: Zig Version
      id: zig-version
      run: echo "version=$(cat .zig-version | tr -d '\n ')" >> $GITHUB_OUTPUT

    - name: Setup Zig
      run: |
        curl -sL "https://ziglang.org/builds/zig-linux-x86_64-${{ steps.zig-version.outputs.version }}.tar.xz" > ${{ runner.temp }}/zig.tar.xz
        tar -xf ${{ runner.temp }}/zig.tar.xz -C ${{ runner.temp }}
        echo "PATH=${{ runner.temp }}/zig-linux-x86_64-${{ steps.zig-version.outputs.version }}:$PATH" >> $GITHUB_ENV
