[package]
name = "enc-roaring"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
enc = { "path" = "../enc" }
linkme = "0.3.22"
croaring = "1.0.1"
num-traits = "0.2.17"
log = "0.4.20"
